tessere.h File Reference
File header contenente le funzioni e le strutture per la gestione di una scacchiera di tessere.
Classes
struct Tessera
Struttura che rappresenta una tessera con due numeri (n1 e n2).
struct Row
Struttura che rappresenta una riga sulla scacchiera di gioco.
Typedefs
typedef struct Tessera Tessera
typedef struct Row Row
Functions
Row * create_row ()
Crea una nuova riga.
void extend_arr_tessere (Row *r)
Estende l'array di tessere in una riga.
Tessera * create_arr_tessere (int size)
Crea un array di tessere.
char * string_tessera (Tessera tessera)
Converte una tessera in una rappresentazione stringa.
bool is_special (Tessera a)
Verifica se una tessera è una tessera speciale.
bool match_left (Tessera a, Tessera b)
Verifica se due tessere possono essere abbinate sul lato sinistro.
bool match_right (Tessera a, Tessera b)
Verifica se due tessere possono essere abbinate sul lato destro.
int * scelte_possibili (Row *piano, int size, Tessera tessera, int *num_scelte)
Genera un array di scelte possibili per posizionare una tessera sulla scacchiera di gioco.
void print_scelte (int *m, int size)
Stampa l'array di scelte per posizionare una tessera.
void print_disponibili (Tessera *tessere, Tessera *speciali, int size_tessere, int size_speciali)
Stampa le tessere disponibili e le tessere speciali.
int max_row (Row *piano, int size)
Trova la dimensione massima tra tutte le righe nella scacchiera di gioco.
void print_giocate (Row *piano, int size)
Stampa lo stato attuale della scacchiera di gioco.
Tessera * remove_tessera (Tessera *tessera, int *size, int index)
Rimuove una tessera da un array di tessere.
void put_front_tessera (Row *piano, int size_piano, Row *r, Tessera tessera)
Posiziona una tessera all'inizio di una riga sulla scacchiera di gioco.
void put_tessera (Row *r, Tessera tessera, int pos)
Posiziona una tessera in una posizione specificata all'interno di una riga sulla scacchiera di gioco.
void put_tessera_speciale (Row *piano, int size_piano, Row *row, int pos, Tessera tessera)
Posiziona una tessera speciale in una posizione specificata all'interno di una riga sulla scacchiera di gioco.
int char_to_int (char *s)
Converte una stringa in un intero.
bool posiziona_tessera (Row *piano, int *size_piano, Tessera tessera)
Verifica se è possibile posizionare una tessera sulla scacchiera di gioco e la posiziona.
Detailed Description
File header contenente le funzioni e le strutture per la gestione di una scacchiera di tessere.
Function Documentation
char_to_int()
int char_to_int (char * s)
Converte una stringa in un intero.
Parameters
s La stringa da convertire.
Returns
Il valore intero ottenuto dalla conversione.
Definition at line 296 of file tessere.c.
                       {
  int sum=0;
  int sign=1;
  int i=0;
  if(s[0]=='-'){
    sign=-1;
    i=1;
  }
  while(i<strlen(s)){
    int cifra=s[i]-48;
    if(cifra<0 || cifra>=10) // se non è una cifra valida restituisco 0;
      return 0;
    sum=sum+cifra*pow(10,strlen(s)-i-1);
    i++;
  }
  return sum*sign;
}
Referenced by game_start(), and posiziona_tessera().
create_arr_tessere()
Tessera* create_arr_tessere (int size)
Crea un array di tessere.
Parameters
size Numero di tessere da creare.
Returns
Un puntatore all'array di tessere.
Definition at line 33 of file tessere.c.
                                     {
  Tessera *new=(Tessera*)malloc(sizeof(Tessera)*size);
  for(int i=0;i<size;i++){
    new[i].n1=-1;
    new[i].n2=-1;
    new[i].selected=false;
    new[i].vertical=false;
  }
  return new;
}
References Tessera::n1.
Referenced by posiziona_tessera().
create_row()
Row* create_row ()
Crea una nuova riga.
Returns
Un puntatore alla nuova riga creata.
Definition at line 9 of file tessere.c.
                 {
  Row *new=(Row*)malloc(sizeof(Row));
  new->capacity=10;
  new->tessere=(Tessera*)malloc(sizeof(Tessera)*new->capacity);
  new->size=0;
  return new;
}
References Row::capacity.
Referenced by game_start_ai().
extend_arr_tessere()
void extend_arr_tessere (Row * r)
Estende l'array di tessere in una riga.
Parameters
r Puntatore alla riga.
Definition at line 18 of file tessere.c.
                               {
  if(r->size>=r->capacity){
    r->tessere=(Tessera*)realloc(r->tessere,sizeof(Tessera)*r->size*2);
    if(!r->tessere) exit(EXIT_FAILURE);
    r->capacity*=2;
    //inizializzo i nuovi spazi con false e -1, perché sono "vuoti"
    for(int i=r->size;i<r->capacity;i++){
      r->tessere[i].n1=-1;
      r->tessere[i].n1=-1;
      r->tessere[i].selected=false;
      r->tessere[i].vertical=false;
    }
  }
}
References Row::capacity, Tessera::n1, Tessera::selected, Row::size, Row::tessere, and Tessera::vertical.
Referenced by posiziona_tessera(), put_front_tessera(), put_tessera(), and put_tessera_speciale().
is_special()
bool is_special (Tessera a)
Verifica se una tessera è una tessera speciale.
Parameters
a La tessera da verificare.
Returns
true se la tessera è speciale, false altrimenti.
Definition at line 44 of file tessere.c.
                          {
  if(a.n1==0 || a.n1==12 || a.n1==11) //indicano se è speciale la tessera
    return true;
  return false;
}
References Tessera::n1.
Referenced by match_left(), match_right(), and posiziona_tessera().
match_left()
bool match_left (Tessera a, Tessera b)
Verifica se due tessere possono essere abbinate sul lato sinistro.
Parameters
a Prima tessera.
b Seconda tessera.
Returns
true se le tessere possono essere abbinate a sinistra, false altrimenti.
Definition at line 50 of file tessere.c.
                                      {
  if(is_special(a) || is_special(b)){
    return true;
  }
  return a.n1 == b.n1 || a.n2 == b.n1;
}
References is_special(), Tessera::n1, and Tessera::n2.
Referenced by game_finished(), posiziona_tessera(), put_tessera(), and scelte_possibili().
match_right()
bool match_right (Tessera a, Tessera b)
Verifica se due tessere possono essere abbinate sul lato destro.
Parameters
a Prima tessera.
b Seconda tessera.
Returns
true se le tessere possono essere abbinate a destra, false altrimenti.
Definition at line 57 of file tessere.c.
                                       {
  if(is_special(a) || is_special(b)){
    return true;
  }
  return a.n1 == b.n2 || a.n2 == b.n2;
}
References is_special(), Tessera::n1, and Tessera::n2.
Referenced by game_finished(), put_tessera(), and scelte_possibili().
max_row()
int max_row (Row * piano, int size)
Trova la dimensione massima tra tutte le righe nella scacchiera di gioco.
Parameters
piano Array di righe che rappresenta la scacchiera di gioco.
size Dimensione dell'array di righe.
Returns
La dimensione massima tra tutte le righe.
Definition at line 133 of file tessere.c.
                                {
  int max=piano[0].size;
  for(int i=1;i<size;i++){
    if(piano[i].size>max){
      max=piano[i].size;
    }
  }
  return max;
}
References Row::size.
Referenced by print_giocate().
posiziona_tessera()
bool posiziona_tessera (Row * piano, int * size_piano, Tessera tessera)
Verifica se è possibile posizionare una tessera sulla scacchiera di gioco e la posiziona.
Parameters
piano Array di righe che rappresenta la scacchiera di gioco.
size_piano Puntatore alla dimensione dell'array di righe.
tessera La tessera da posizionare.
Returns
true se la tessera è stata posizionata con successo, false altrimenti.
Definition at line 314 of file tessere.c.
                                                                  {
  Row *r_0=&piano[0];
  if(r_0->size==0){
    r_0->tessere[0]=tessera;
    r_0->size=1;
    return true;
  }
  int num_scelte=0;
  int *scelte=scelte_possibili(piano,*size_piano,tessera,&num_scelte);
  int s;
  if(num_scelte<=0){
    return false;
  }
  printf("Tessera scelta: [%d|%d]\n",tessera.n1,tessera.n2);
  if(num_scelte>1){
    char keys[10];
    do{
        printf("Scelte possibili:\n");
        print_scelte(scelte,num_scelte);
        scanf("%s",keys);
        s=char_to_int(keys);
   }while(s<=0 || s>num_scelte);
   s=s-1; //per sistemare l'index, si accettano in input valori da 1 a x, per sistemare l'index devo fare -1
  }else{
    s=0; //se la scelta è solo 1 la inserisco in automatico
  }
  int pos=scelte[s*2+1]; //num col
  int num_row=scelte[s*2]; //num row
  Row *r=&piano[num_row];
  //put_tessera()
  if(pos>=0){
    //put_first()
    if(is_special(tessera)){
      put_tessera_speciale(piano,*size_piano,r,pos,tessera);
    }else{
      put_tessera(r,tessera,pos);
    }
  }else{ //pos=-1
    //put_tessera
    if(is_special(tessera)){
      put_tessera_speciale(piano,*size_piano,r,pos,tessera);
    }else{
      put_front_tessera(piano,*size_piano,r,tessera);
    }
    pos=0;
  }
  if(num_row+1>=*size_piano || !piano[num_row+1].tessere[pos].selected){
    char scelta=0;
    while(scelta!='v' && scelta!='h'){
      printf("Digita v o h (v=vertical e h=horizontal)\n");
      scanf(" %c",&scelta);
    }
    if(scelta=='v'){
      if(num_row+1>=*size_piano){
        ++*size_piano;
        piano[num_row+1].tessere=create_arr_tessere(r->size);
        piano[num_row+1].size=r->size;
      }
      Row *under_row=&piano[num_row+1];
      if(r->size>under_row->size){
        int old_size=under_row->size;
        under_row->size=r->size;
        extend_arr_tessere(under_row);
        for(int i=old_size;i<under_row->size;i++){
          under_row->tessere[i].n1=-1;
          under_row->tessere[i].n1=-1;
          under_row->tessere[i].selected=false;
          under_row->tessere[i].vertical=false;
        }
        
      }
      r->tessere[pos].vertical=true;
      //[3|1]
      if(pos+1<r->size && match_left(r->tessere[pos],r->tessere[pos+1])){
        if (r->tessere[pos].n2 == r->tessere[pos+1].n1 && r->tessere[pos+1].n1!=0) { //se è tessera [0|0] mettila com'è
          int n2=r->tessere[pos].n2;
          r->tessere[pos].n2=r->tessere[pos].n1;
          r->tessere[pos].n1=n2;
        }
      }
      under_row->tessere[pos]=r->tessere[pos];
      r->tessere[pos].n2=r->tessere[pos].n1; //per la tessera in alto voglio lasciare invariato solo n1, n2 sarà uguale ad n1 avranno lo stesso valore per comodità
      under_row->tessere[pos].n1=under_row->tessere[pos].n2; // per la tessera più in alto voglio lasciare invariato solo n2, n1 sarà uguale ad n1
    }
  }
  free(scelte);
  return true;
}
References char_to_int(), create_arr_tessere(), extend_arr_tessere(), is_special(), match_left(), Tessera::n1, Tessera::n2, print_scelte(), put_front_tessera(), put_tessera(), put_tessera_speciale(), scelte_possibili(), Tessera::selected, Row::size, Row::tessere, and Tessera::vertical.
Referenced by game_start().
print_disponibili()
void print_disponibili (Tessera * tessere, Tessera * speciali, int size_tessere, int size_speciali)
Stampa le tessere disponibili e le tessere speciali.
Parameters
tessere Array di tessere.
speciali Array di tessere speciali.
size_tessere Dimensione dell'array di tessere.
size_speciali Dimensione dell'array di tessere speciali.
Definition at line 110 of file tessere.c.
                                                                                                   {
  printf("Tessere disponibili:\n");
  int righe = 10;
  int col = ((size_tessere) / righe) + 1;
  int resto_last_col = (size_tessere) % righe;
  for (int i = 0; i < righe; i++) {
    if (resto_last_col == i) {
      col--;
    }
    for (int j = 0; j < col; j++) {
      printf("%d. [%d|%d]\t", tessere[i + j * 10].num, tessere[i + j * 10].n1, tessere[i + j * 10].n2);
    }
    printf("\n");
  }
  if (size_speciali > 0) {
    printf("---TESSERE SPECIALI----\n");
    for (int i = 0; i < size_speciali; i++) {
      printf("-%d. [%d|%d]\n", i + 1, speciali[i].n1, speciali[i].n2);
    }
  }
  printf("\n");
}
Referenced by game_start_ai().
print_giocate()
void print_giocate (Row * piano, int size)
Stampa lo stato attuale della scacchiera di gioco.
Parameters
piano Array di righe che rappresenta la scacchiera di gioco.
size Dimensione dell'array di righe.
Definition at line 143 of file tessere.c.
                                          {
  printf("Tessere giocate:\n");
  printf("\t ");
  for(int i=0;i<max_row(piano,size);i++){
    printf("%d\t ",i);
  }
  printf("%d\n",max_row(piano,size));
  for(int i=0;i<size;i++){
    Tessera *a=piano[i].tessere;
    int size_a=piano[i].size;
    printf("%d\t",i);
    for(int j=0;j<size_a;j++){
      if(a[j].vertical && a[j].selected){
          printf(" [%d]\t",a[j].n1);
      }else{
        if(a[j].selected){
          printf("[%d|%d]\t",a[j].n1,a[j].n2);
        }else{
          printf(" \t");
        }
      }
    }
    printf("\n");
  }
  printf("\n\n");
}
References max_row(), Row::size, and Row::tessere.
Referenced by game_start_ai().
print_scelte()
void print_scelte (int * m, int size)
Stampa l'array di scelte per posizionare una tessera.
Parameters
m Array di scelte.
size Dimensione dell'array.
Definition at line 102 of file tessere.c.
                                  {
  int k=0;
  for(int i=0;i<size;i++){
    printf("%d. {%d,%d}\n",i+1,m[k],m[k+1]);
    k=k+2;
  }
}
Referenced by posiziona_tessera().
put_front_tessera()
void put_front_tessera (Row * piano, int size_piano, Row * r, Tessera tessera)
Posiziona una tessera all'inizio di una riga sulla scacchiera di gioco.
Parameters
piano Array di righe che rappresenta la scacchiera di gioco.
size_piano Puntatore alla dimensione dell'array di righe.
r Puntatore alla riga in cui posizionare la tessera.
tessera La tessera da posizionare.
Definition at line 192 of file tessere.c.
                                                                        {
  for(int i=0;i<size_piano;i++){
    Row *row=&piano[i];
    extend_arr_tessere(row);
    for(int j=row->size-1;j>=0;j--){
      row->tessere[j+1]=row->tessere[j];
    }
    row->tessere[0].n1=-1;
    row->tessere[0].n2=-1;
    row->tessere[0].selected=false;
    row->tessere[0].vertical=false;
    ++row->size;
  }
  if(tessera.n2!=r->tessere[1].n1){
    int n2=tessera.n2;
    tessera.n2=tessera.n1;
    tessera.n1=n2;
  }
  r->tessere[0]=tessera;
}
References extend_arr_tessere(), Tessera::n1, Tessera::n2, Tessera::selected, Row::size, Row::tessere, and Tessera::vertical.
Referenced by first_match(), posiziona_tessera(), and put_tessera_speciale().
put_tessera()
void put_tessera (Row * r, Tessera tessera, int pos)
Posiziona una tessera in una posizione specificata all'interno di una riga sulla scacchiera di gioco.
Parameters
r Puntatore alla riga in cui posizionare la tessera.
tessera La tessera da posizionare.
pos Posizione in cui posizionare la tessera.
Definition at line 213 of file tessere.c.
                                                {
  if(pos>=r->size){
    extend_arr_tessere(r);
    ++r->size;
  }
   //metto a sinistra la tessera
  if(r->tessere[pos+1].selected && match_left(tessera,r->tessere[pos+1])){
    if (tessera.n2 != r->tessere[pos+1].n1 && r->tessere[pos+1].n1!=0) { //se è tessera [0|0] mettila com'è
      int n2=tessera.n2;
      tessera.n2=tessera.n1;
      tessera.n1=n2;
    }
  }
  
  
   //metto a destra la tessera
  if(pos>0 && r->tessere[pos-1].selected && match_right(tessera,r->tessere[pos-1])){
    if(tessera.n1 !=r->tessere[pos-1].n2 && r->tessere[pos-1].n1!=0){
      int n2=tessera.n2;
      tessera.n2=tessera.n1;
      tessera.n1=n2;
    }
  }
  //tessera.selected=true;
  r->tessere[pos]=tessera;
}
References extend_arr_tessere(), match_left(), match_right(), Tessera::n1, Tessera::n2, Tessera::selected, Row::size, and Row::tessere.
Referenced by first_match(), and posiziona_tessera().
put_tessera_speciale()
void put_tessera_speciale (Row * piano, int size_piano, Row * row, int pos, Tessera tessera)
Posiziona una tessera speciale in una posizione specificata all'interno di una riga sulla scacchiera di gioco.
Parameters
piano Array di righe che rappresenta la scacchiera di gioco.
size_piano Puntatore alla dimensione dell'array di righe.
row Puntatore alla riga in cui posizionare la tessera speciale.
pos Posizione in cui posizionare la tessera speciale.
tessera La tessera speciale da posizionare.
Definition at line 249 of file tessere.c.
                                                                                     {
  if(pos>=row->size){
    extend_arr_tessere(row);
    ++row->size;
  }
  if(tessera.n1==11){
    //sommo 1 a tutte le tessere
    for(int i=0;i<size_piano;i++){
      Row *r=&piano[i];
      Tessera *tessere=r->tessere;
      for(int j=0;j<r->size;j++){
        //se 4%6=4 e 4+1=5, quindi va bene
        //se 6%6=0 e 0+1=1, quindi va bene
        tessere[j].n1=(tessere[j].n1%6)+1;
        tessere[j].n2=(tessere[j].n2%6)+1;
      }
    }
    
    if(pos>0 && row->tessere[pos-1].selected){
      tessera.n1=row->tessere[pos-1].n2;
      tessera.n2=row->tessere[pos-1].n2;
    }else if(row->tessere[pos+1].selected){
      tessera.n1=row->tessere[pos+1].n1;
      tessera.n2=row->tessere[pos+1].n1;
    }
  }
  if(tessera.n1==12){
    if(pos>0 && row->tessere[pos-1].selected){
      tessera.n1=row->tessere[pos-1].n2;
      tessera.n2=row->tessere[pos-1].n1;
    } else if(row->tessere[pos+1].selected){
      tessera.n1=row->tessere[pos+1].n2;
      tessera.n2=row->tessere[pos+1].n1;
    }
  }
  //se è zero inserisco normalmente
  if(pos<0){
    put_front_tessera(piano,size_piano,row,tessera);
    return;
  }
 // tessera.selected=true;
  row->tessere[pos]=tessera;
}
References extend_arr_tessere(), Tessera::n1, Tessera::n2, put_front_tessera(), Tessera::selected, Row::size, and Row::tessere.
Referenced by posiziona_tessera().
remove_tessera()
Tessera* remove_tessera (Tessera * tessera, int * size, int index)
Rimuove una tessera da un array di tessere.
Parameters
tessera Array di tessere.
size Puntatore alla dimensione dell'array.
index Indice della tessera da rimuovere.
Returns
Un nuovo array di tessere allocato dinamicamente con la tessera specificata rimossa.
Definition at line 174 of file tessere.c.
                                                                  {
  Tessera * new_arr = (Tessera *) malloc(sizeof(Tessera) * (*size - 1));
  if (!new_arr) exit(EXIT_FAILURE);
  int j = 0;
  for (int i = 0; i < *size; i++) {
    if (i != index) {
      new_arr[j] = tessera[i];
      ++j;
    }
  }
  for (int i = 0; i < *size - 1; i++) {
    new_arr[i].num = i + 1; //aggiorno numero relativo all'interfaccia utente, cioè i numeri che scelgo da tastiera
  }
  --*size;
  free(tessera); //libero la vecchia memoria allocata
  return new_arr;
}
References Tessera::num.
Referenced by first_match(), game_start(), and game_start_ai().
scelte_possibili()
int* scelte_possibili (Row * piano, int size, Tessera tessera, int * num_scelte)
Genera un array di scelte possibili per posizionare una tessera sulla scacchiera di gioco.
Parameters
piano Array di righe che rappresenta la scacchiera di gioco.
size Dimensione dell'array di righe.
tessera La tessera da posizionare.
num_scelte Parametro di output per memorizzare il numero di scelte.
Returns
Un array allocato dinamicamente di interi che rappresenta le scelte.
Definition at line 65 of file tessere.c.
                                                                          {
  
  int *scelte=(int*)malloc(sizeof(int)*size*100);
  int k=0;
  /*
  int scelte={{1,2},
              {0,1},
              {1,1}}
  */
  for(int i=0;i<size;i++){
    Tessera *a=piano[i].tessere;
    int a_size=piano[i].size;
    for(int j=0;j<a_size;j++){
      if(a[j].selected){
        if((j==0 || !a[j-1].selected) && match_left(tessera,a[j])){
          scelte[k]=i;
          scelte[k+1]=j-1;
          k=k+2;
          
        }
        if((j==a_size-1 || !a[j+1].selected) && match_right(tessera,a[j])){
            scelte[k]=i;
            scelte[k+1]=j+1;
            k=k+2;
        }
      }
    }
  }
  *num_scelte=k/2;
  if(k>0){
    scelte=(int*)realloc(scelte,sizeof(int)* k);
    if(!scelte) exit(EXIT_FAILURE);
  }
  return scelte;
}
References match_left(), match_right(), Row::size, and Row::tessere.
Referenced by first_match(), and posiziona_tessera().
string_tessera()
char* string_tessera (Tessera tessera)
Converte una tessera in una rappresentazione stringa.
Parameters
tessera La tessera da convertire.
Returns
Una stringa allocata dinamicamente che rappresenta la tessera.